Repository ROCm/composable_kernel, pull requests merged in 2022-06, with the labels that each got.

#274 Regulate reduction accumulator operations and Element-wise operations
  example/12_reduce/reduce_blockwise.cpp
  example/12_reduce/reduce_blockwise_two_call.cpp
  example/13_pool2d_fwd/pool2d_fwd_common.hpp
  example/16_gemm_reduce/gemm_reduce_xdl_max_fp16.cpp
  example/16_gemm_reduce/gemm_reduce_xdl_mean_squaremean_fp16.cpp
  example/18_batched_gemm_reduce/batched_gemm_reduce_xdl_fp16.cpp
  example/19_binary_elementwise/broadcast_add_2d_amn_bn.cpp
  example/19_binary_elementwise/broadcast_add_3d_am_bmnk.cpp
  example/19_binary_elementwise/elementwise_add_1d.cpp
  example/19_binary_elementwise/elementwise_add_4d.cpp
  example/21_gemm_layernorm/gemm_bias_relu_add_layernorm_xdl_fp16.cpp
  example/21_gemm_layernorm/gemm_layernorm_xdl_fp16.cpp
  include/ck/tensor_operation/gpu/device/device_base.hpp
  include/ck/tensor_operation/gpu/device/device_cgemm_4gemm_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_pool2d_fwd_nhwc_nhwc.hpp
  include/ck/tensor_operation/gpu/device/device_reduce_multiblock.hpp
  include/ck/tensor_operation/gpu/device/reduction_operator_mapping.hpp
  include/ck/tensor_operation/gpu/element/binary_element_wise_operation.hpp
  include/ck/tensor_operation/gpu/element/element_wise_operation.hpp
  include/ck/tensor_operation/gpu/element/unary_element_wise_operation.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_2d_reduction_multiblock.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_2d_reduction_threadwise.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_bias_add_reduce_xdl_cshuffle_v1.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_reduce_xdl_cshuffle_v1.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_set_buffer_value.hpp
  include/ck/utility/reduction_operator.hpp
  library/include/ck/library/host_tensor/host_reduction.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_conv_bwd_data.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_gemm_bias_2d.hpp
  library/include/ck/library/tensor_operation_instance/gpu/reduce/device_reduce_instance_blockwise.hpp
  library/include/ck/library/tensor_operation_instance/gpu/reduce/device_reduce_instance_multiblock_atomic_add.hpp
  library/include/ck/library/tensor_operation_instance/gpu/reduce/device_reduce_instance_threadwise.hpp
  library/src/tensor_operation_instance/gpu/batched_gemm_reduce/device_batched_gemm_reduce_xdl_cshuffle_f16_f16_f16_f32_f32_gkm_gkn_gmn_instance.cpp
  library/src/tensor_operation_instance/gpu/batched_gemm_reduce/device_batched_gemm_reduce_xdl_cshuffle_f16_f16_f16_f32_f32_gkm_gnk_gmn_instance.cpp
  library/src/tensor_operation_instance/gpu/batched_gemm_reduce/device_batched_gemm_reduce_xdl_cshuffle_f16_f16_f16_f32_f32_gmk_gkn_gmn_instance.cpp
  library/src/tensor_operation_instance/gpu/batched_gemm_reduce/device_batched_gemm_reduce_xdl_cshuffle_f16_f16_f16_f32_f32_gmk_gnk_gmn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_bias_add_reduce/device_gemm_bias_add_reduce_xdl_cshuffle_f16_f16_f16_f32_f32_km_kn_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_bias_add_reduce/device_gemm_bias_add_reduce_xdl_cshuffle_f16_f16_f16_f32_f32_km_nk_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_bias_add_reduce/device_gemm_bias_add_reduce_xdl_cshuffle_f16_f16_f16_f32_f32_mk_kn_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_bias_add_reduce/device_gemm_bias_add_reduce_xdl_cshuffle_f16_f16_f16_f32_f32_mk_nk_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_reduce/device_gemm_reduce_xdl_cshuffle_f16_f16_f16_f32_f32_km_kn_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_reduce/device_gemm_reduce_xdl_cshuffle_f16_f16_f16_f32_f32_km_nk_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_reduce/device_gemm_reduce_xdl_cshuffle_f16_f16_f16_f32_f32_mk_kn_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_reduce/device_gemm_reduce_xdl_cshuffle_f16_f16_f16_f32_f32_mk_nk_mn_instance.cpp
  profiler/include/profile_batched_gemm_reduce_impl.hpp
  profiler/include/profile_gemm_bias_add_reduce_impl.hpp
  profiler/include/profile_gemm_reduce_impl.hpp
  profiler/include/profile_reduce_impl.hpp
Labels: code quality, CI Passes

#229 Create MIT LICENSE
  LICENSE
  include/ck/config.hpp
Labels: CI Passes

#259 Testing all fwd convolution specializations.
  example/09_convnd_fwd/convnd_fwd_xdl_fp16.cpp
  include/ck/config.hpp
  library/include/ck/library/utility/check_err.hpp
  library/include/ck/library/utility/conv_util.hpp
  library/include/ck/library/utility/fill.hpp
  library/include/ck/library/utility/op_instance_engine.hpp
  library/src/tensor_operation_instance/gpu/conv1d_fwd/device_conv1d_fwd_xdl_nwc_kxc_nwk_bf16_instance.cpp
  library/src/tensor_operation_instance/gpu/conv2d_fwd/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/conv2d_fwd/device_convnd_2d_fwd_xdl_nhwc_kyxc_nhwk_bf16_instance.cpp
  library/src/tensor_operation_instance/gpu/conv2d_fwd/device_convnd_2d_fwd_xdl_nhwc_kyxc_nhwk_f16_instance.cpp
  library/src/tensor_operation_instance/gpu/conv2d_fwd/device_convnd_2d_fwd_xdl_nhwc_kyxc_nhwk_f32_instance.cpp
  library/src/tensor_operation_instance/gpu/conv2d_fwd/device_convnd_2d_fwd_xdl_nhwc_kyxc_nhwk_int8_instance.cpp
  library/src/tensor_operation_instance/gpu/conv3d_fwd/device_conv3d_fwd_xdl_ndhwc_kzyxc_ndhwk_bf16_instance.cpp
  profiler/src/profile_convnd_fwd.cpp
  script/profile_conv.sh
  test/convnd_fwd/CMakeLists.txt
  test/convnd_fwd/conv1d_fwd.cpp
  test/convnd_fwd/conv2d_fwd.cpp
  test/convnd_fwd/conv3d_fwd.cpp
  test/convnd_fwd/conv_util.hpp
Labels: CI Passes

#313 Grouped Gemm ckProfiler hotfix
  profiler/include/profile_grouped_gemm_impl.hpp
Labels: bug
