Repository ROCm/composable_kernel, pull requests merged in 2022-11, with the labels that each got.

#471 Conv perlayer int8 quantization
  client_example/09_quantization/CMakeLists.txt
  client_example/09_quantization/conv2d_fwd_bias_relu_perlayer_quantization.cpp
  client_example/09_quantization/conv2d_fwd_perlayer_quantization.cpp
  example/14_gemm_xdl_quantization/CMakeLists.txt
  example/14_gemm_xdl_quantization/gemm_xdl_relu_quantization_int8.cpp
  example/14_gemm_xdl_requant_relu_requant/CMakeLists.txt
  example/44_conv2d_fwd_quant/CMakeLists.txt
  example/44_conv2d_fwd_quant/conv2d_fwd_xdl_bias_relu_perlayer_quantization_int8.cpp
  example/44_conv2d_fwd_quant/conv2d_fwd_xdl_perlayer_quantization_int8.cpp
  include/ck/tensor_operation/gpu/element/element_wise_operation.hpp
  include/ck/tensor_operation/gpu/element/quantization_operation.hpp
  include/ck/tensor_operation/gpu/element/unary_element_wise_operation.hpp
  library/include/ck/library/tensor_operation_instance/device_operation_instance_factory.hpp
  library/include/ck/library/tensor_operation_instance/gpu/grouped_convolution_bias_forward_perlayer_quantization.hpp
  library/include/ck/library/tensor_operation_instance/gpu/grouped_convolution_forward_perlayer_quantization.hpp
  library/src/tensor_operation_instance/gpu/quantization/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/quantization/device_conv2d_xdl_bias_quant_int8_instance.cpp
  library/src/tensor_operation_instance/gpu/quantization/device_conv2d_xdl_quant_int8_instance.cpp
  script/cmake-ck-dev.sh
  script/cmake-ck-release.sh
Labels: CI - Pass

#497 Refine layernorm naming and test code
  client_example/05_layernorm/layernorm2d.cpp
  example/27_layernorm/layernorm_blockwise.cpp
  example/42_groupnorm/groupnorm_sigmoid_fp16.cpp
  include/ck/tensor_operation/gpu/device/device_normalization.hpp
  include/ck/tensor_operation/gpu/device/impl/device_normalization_impl.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_normalization_naive_variance.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_normalization_welford_variance.hpp
  profiler/include/profile_groupnorm_impl.hpp
  profiler/include/profile_layernorm_impl.hpp
  test/normalization/CMakeLists.txt
  test/normalization/test_groupnorm_fp16.cpp
  test/normalization/test_groupnorm_fp32.cpp
  test/normalization/test_layernorm2d_fp16.cpp
  test/normalization/test_layernorm2d_fp32.cpp
  test/normalization/test_layernorm2d_util.hpp
Labels: CI - Pass

#509 Client examples AddFastGelu and FastGelu + instances.
  client_example/02_gemm_add_add_fastgelu/CMakeLists.txt
  client_example/02_gemm_add_add_fastgelu/gemm_add_fastgelu.cpp
  client_example/02_gemm_add_add_fastgelu/gemm_fastgelu.cpp
  include/ck/tensor_operation/gpu/element/unary_element_wise_operation.hpp
  library/include/ck/library/tensor_operation_instance/device_operation_instance_factory.hpp
  library/include/ck/library/tensor_operation_instance/gpu/gemm_add_fastgelu.hpp
  library/include/ck/library/tensor_operation_instance/gpu/gemm_fastgelu.hpp
  library/src/tensor_operation_instance/gpu/gemm_add_fastgelu/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/gemm_add_fastgelu/device_gemm_add_fastgelu_xdl_c_shuffle_f16_f16_f16_f16_km_kn_mn_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_add_fastgelu/device_gemm_add_fastgelu_xdl_c_shuffle_f16_f16_f16_f16_km_nk_mn_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_add_fastgelu/device_gemm_add_fastgelu_xdl_c_shuffle_f16_f16_f16_f16_mk_kn_mn_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_add_fastgelu/device_gemm_add_fastgelu_xdl_c_shuffle_f16_f16_f16_f16_mk_nk_mn_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_fastgelu/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/gemm_fastgelu/device_gemm_fastgelu_xdl_c_shuffle_f16_f16_f16_km_kn_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_fastgelu/device_gemm_fastgelu_xdl_c_shuffle_f16_f16_f16_km_nk_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_fastgelu/device_gemm_fastgelu_xdl_c_shuffle_f16_f16_f16_mk_kn_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_fastgelu/device_gemm_fastgelu_xdl_c_shuffle_f16_f16_f16_mk_nk_mn_instance.cpp
Labels: CI - Pass

#516 Remove int8 from batchnorm-forward instances
  library/include/ck/library/tensor_operation_instance/gpu/batchnorm_forward.hpp
  library/src/tensor_operation_instance/gpu/batchnorm/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/batchnorm/device_batchnorm_forward_i8_instance.cpp
  profiler/include/profile_batchnorm_forward_impl.hpp
  profiler/src/profile_batchnorm_fwd.cpp
  test/batchnorm_fwd/batchnorm_fwd_rank_4.cpp
Labels: priority

#231 Fix split-k gemm test
  test/gemm_split_k/gemm_split_k.cpp
Labels: bug
