Repository ROCm/composable_kernel, pull requests merged in 2022-04, with the labels that each got.

#152 Improve Reduction kernel api
  include/ck/tensor_operation/gpu/block/reduction_functions_blockwise.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_2d_reduction_blockwise.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_2d_reduction_multiblock_atomic_add.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_2d_reduction_multiblock_partial_reduce.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_2d_reduction_threadwise.hpp
  include/ck/tensor_operation/gpu/thread/reduction_functions_threadwise.hpp
Labels: CI Passes

#176 Fix typo in batched gemm profiler
  profiler/include/profile_batched_gemm_impl.hpp
  profiler/src/profile_batched_gemm.cpp
Labels: bug

#183 Convolution FWD profiler refactor.
  example/06_conv2d_fwd_bias_relu/CMakeLists.txt
  example/07_conv2d_fwd_bias_relu_add/CMakeLists.txt
  example/09_convnd_fwd/CMakeLists.txt
  example/10_conv2d_bwd_data/CMakeLists.txt
  example/11_conv2d_bwd_weight/CMakeLists.txt
  example/17_convnd_bwd_data_xdl/CMakeLists.txt
  library/CMakeLists.txt
  library/include/ck/library/utility/conv_fwd_util.hpp
  library/include/ck/library/utility/fill.hpp
  library/include/ck/library/utility/op_instance_engine.hpp
  library/src/utility/CMakeLists.txt
  library/src/utility/conv_fwd_util.cpp
  profiler/CMakeLists.txt
  profiler/include/profile_conv_fwd_impl.hpp
  profiler/include/profile_convnd_fwd.hpp
  profiler/src/profile_conv_fwd.cpp
  profiler/src/profile_convnd_bwd_data.cpp
  profiler/src/profile_convnd_fwd.cpp
  profiler/src/profiler.cpp
  test/conv2d_bwd_weight/CMakeLists.txt
  test/conv_util/CMakeLists.txt
  test/convnd_bwd_data/CMakeLists.txt
  test/convnd_fwd/CMakeLists.txt
  test/convnd_fwd/conv1d_fwd.cpp
  test/convnd_fwd/conv2d_fwd.cpp
  test/convnd_fwd/conv3d_fwd.cpp
  test/convnd_fwd/conv_util.hpp
  test/reference_conv_fwd/CMakeLists.txt
  test/reference_conv_fwd/reference_conv_fwd.cpp
Labels: CI Passes

#187 Use inline asm for 4x4 int8 transposition
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v3r1.hpp
  include/ck/utility/transpose_vectors.hpp
Labels: CI Passes

#181 Clang-format only modified files.
  script/clang-format-overwrite.sh
Labels: code quality

#186 add comments to batched_gemm
  include/ck/tensor_operation/gpu/device/device_batched_gemm_xdl.hpp
  include/ck/tensor_operation/gpu/device/device_conv3d_fwd_xdl_ndhwc_kzyxc_ndhwk.hpp
Labels: documentation, CI Passes
