Repository ROCm/composable_kernel, pull requests merged in 2022-09, with the labels that each got.

#396 Softmax client example
  client_example/06_softmax/CMakeLists.txt
  client_example/06_softmax/softmax4d.cpp
  client_example/CMakeLists.txt
  example/23_softmax/softmax_blockwise.cpp
  include/ck/tensor_operation/gpu/device/device_softmax.hpp
  include/ck/tensor_operation/gpu/device/impl/device_softmax_impl.hpp
  library/include/ck/library/tensor_operation_instance/gpu/softmax.hpp
  library/src/tensor_operation_instance/gpu/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/normalization/device_softmax_f16_f16_instance.cpp
  library/src/tensor_operation_instance/gpu/normalization/device_softmax_f32_f32_instance.cpp
  profiler/include/profile_normalization_impl.hpp
  profiler/src/profile_normalization.cpp
  test/softmax/test_softmax_util.hpp
Labels: CI - Testing

#395 Fused attention instances & padding tests
  example/32_batched_gemm_scale_softmax_gemm/CMakeLists.txt
  example/32_batched_gemm_scale_softmax_gemm/padded_batched_gemm_scale_softmax_gemm_xdl_fp16.cpp
  include/ck/ck.hpp
  include/ck/tensor_operation/gpu/block/blockwise_softmax.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_gemm_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_softmax_gemm_permute_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_softmax_gemm_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_gemm_xdl_cshuffle_v1.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_softmax_gemm_xdl_cshuffle_v1.hpp
  library/src/tensor_operation_instance/gpu/batched_gemm_gemm/device_batched_gemm_gemm_xdl_cshuffle_f16_f16_f16_f16_gmk_gnk_gno_gmo_instance.cpp
  library/src/tensor_operation_instance/gpu/batched_gemm_softmax_gemm/device_batched_gemm_softmax_gemm_xdl_cshuffle_f16_f16_f16_f16_gmk_gnk_gno_gmo_instance.cpp
  profiler/include/profile_batched_gemm_softmax_gemm_impl.hpp
  test/batched_gemm_gemm/test_batched_gemm_gemm_fp16.cpp
  test/batched_gemm_softmax_gemm/test_batched_gemm_softmax_gemm_fp16.cpp
  test/batched_gemm_softmax_gemm/test_batched_gemm_softmax_gemm_util.hpp
Labels: CI - Pass

#402 Add stderr to QA logfiles, process splitK and ONNX gemm kernels
  Jenkinsfile
  script/process_perf_data.py
  script/process_qa_data.sh
  script/profile_onnx_gemm.sh
  script/run_full_performance_tests.sh
Labels: CI - Testing

#409 Fix gemm-softmax-gemm-permute padding cases
  example/32_batched_gemm_scale_softmax_gemm/batched_gemm_scale_softmax_gemm_permute_xdl_fp16.cpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_softmax_gemm_permute_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_gemm_xdl_cshuffle_v1.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_softmax_gemm_xdl_cshuffle_v1.hpp
Labels: CI - Failed

#405 embedding fuse layernorm
  example/36_sparse_embedding/CMakeLists.txt
  example/36_sparse_embedding/sparse_embedding3_forward_layernorm.cpp
  example/CMakeLists.txt
  include/ck/tensor_operation/gpu/device/device_sparse_embedding3_forward_layernorm.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_sparse_embedding3_forward_layernorm.hpp
  include/ck/utility/amd_buffer_addressing.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_sparse_embedding3_forward_layernorm.hpp
Labels: CI - Testing

#394 batched_gemm + multiple_d + gemm + multiple_d
  example/37_batched_gemm_add_add_relu_gemm_add/CMakeLists.txt
  example/37_batched_gemm_add_add_relu_gemm_add/batched_gemm_add_add_relu_gemm_add_xdl_fp16.cpp
  example/CMakeLists.txt
  include/ck/tensor_operation/gpu/device/device_batched_gemm_multiple_d_gemm_multiple_d.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_multiple_d_gemm_multiple_d_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/matrix_padder.hpp
  include/ck/tensor_operation/gpu/element/binary_element_wise_operation.hpp
  include/ck/tensor_operation/gpu/element/unary_element_wise_operation.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_multiple_d_gemm_multiple_d_xdl_cshuffle_v1.hpp
  library/include/ck/library/tensor_operation_instance/gpu/batched_gemm_add_relu_gemm_add.hpp
  library/src/tensor_operation_instance/gpu/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/batched_gemm_add_relu_gemm_add/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/batched_gemm_add_relu_gemm_add/device_batched_gemm_add_relu_gemm_add_xdl_cshuffle_f16_f16_f16_f16_gmk_gnk_gno_gmo_instance.cpp
  library/src/tensor_operation_instance/gpu/batched_gemm_add_relu_gemm_add/device_batched_gemm_add_relu_gemm_add_xdl_cshuffle_f16_f16_f16_f16_gmk_gnk_gon_gmo_instance.cpp
  profiler/CMakeLists.txt
  profiler/include/profile_batched_gemm_add_relu_gemm_add_impl.hpp
  profiler/src/profile_batched_gemm_add_relu_gemm_add.cpp
  profiler/src/profile_batched_gemm_gemm.cpp
  profiler/src/profiler.cpp
Labels: CI - Testing

#416 Use intrinsic instead of inline asm for in-register transpose
  include/ck/utility/transpose_vectors.hpp
Labels: priority

#424 Add batched attention special kernel instances
  include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_softmax_gemm_xdl_cshuffle_v1.hpp
  library/src/tensor_operation_instance/gpu/batched_gemm_softmax_gemm/device_batched_gemm_softmax_gemm_xdl_cshuffle_f16_f16_f16_f16_gmk_gnk_gno_gmo_instance.cpp
  test/batched_gemm_softmax_gemm/test_batched_gemm_softmax_gemm_fp16.cpp
  test/batched_gemm_softmax_gemm/test_batched_gemm_softmax_gemm_util.hpp
Labels: CI - Testing, priority

#408 Add 'Permute' device op & example
  example/39_permute/CMakeLists.txt
  example/39_permute/common.hpp
  example/39_permute/permute_1xHxW_fp16.cpp
  example/39_permute/permute_HxWx4_fp16.cpp
  example/39_permute/permute_NxHxW_fp16.cpp
  example/39_permute/run_permute_bundle_example.inc
  example/39_permute/run_permute_element_example.inc
  include/ck/tensor_operation/gpu/device/device_base.hpp
  include/ck/tensor_operation/gpu/device/device_elementwise.hpp
  include/ck/tensor_operation/gpu/device/device_permute.hpp
  include/ck/tensor_operation/gpu/device/impl/device_permute_impl.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_elementwise_1d.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_permute.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v3r1.hpp
  include/ck/utility/span.hpp
  library/include/ck/library/utility/check_err.hpp
  library/include/ck/library/utility/fill.hpp
  library/include/ck/library/utility/host_tensor.hpp
Labels: CI - Testing, priority

#417 Group norm
  client_example/05_layernorm/layernorm2d.cpp
  example/42_groupnorm/CMakeLists.txt
  example/42_groupnorm/groupnorm_sigmoid_fp16.cpp
  include/ck/tensor_operation/gpu/device/device_layernorm_impl.hpp
  include/ck/tensor_operation/gpu/element/unary_element_wise_operation.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_layernorm_naive_variance.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_layernorm_welford_variance.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_groupnorm.hpp
  library/include/ck/library/tensor_operation_instance/gpu/layernorm.hpp
  library/src/tensor_operation_instance/gpu/normalization/device_layernorm_f16_instance.cpp
  library/src/tensor_operation_instance/gpu/normalization/device_layernorm_f32_instance.cpp
  profiler/CMakeLists.txt
  profiler/include/profile_groupnorm_impl.hpp
  profiler/src/profile_groupnorm.cpp
  profiler/src/profile_layernorm.cpp
  profiler/src/profiler.cpp
  test/layernorm/CMakeLists.txt
  test/layernorm/test_groupnorm_fp16.cpp
  test/layernorm/test_groupnorm_fp32.cpp
  test/layernorm/test_layernorm2d_fp16.cpp
  test/layernorm/test_layernorm2d_fp32.cpp
  test/layernorm/test_layernorm2d_util.hpp
  test/layernorm/test_layernorm_fp16.cpp
  test/layernorm/test_layernorm_fp32.cpp
Labels: CI - Testing, priority

#418 Fix device instance libarary to include all instances
  library/src/tensor_operation_instance/gpu/CMakeLists.txt
  requirements.txt
Labels: CI - Testing
