Repository ROCm/composable_kernel, pull requests merged in 2022-08, with the labels that each got.

#349 Add batched/grouped_gemm contraction deviceOps
  example/25_gemm_bias_e_permute/CMakeLists.txt
  example/25_gemm_bias_e_permute/gemm_bias_e_permute_m2n3_xdl_fp16.cpp
  example/25_gemm_bias_e_permute/gemm_bias_e_permute_m3n2_xdl_fp16.cpp
  example/25_gemm_bias_e_permute/gemm_bias_e_permute_xdl_fp16.cpp
  example/28_grouped_gemm_bias/CMakeLists.txt
  example/28_grouped_gemm_bias/grouped_gemm_bias_xdl_fp16.cpp
  example/28_grouped_gemm_bias_e_permute/CMakeLists.txt
  example/28_grouped_gemm_bias_e_permute/grouped_gemm_bias_e_permute_xdl_fp16.cpp
  example/29_batched_gemm_bias_e_permute/CMakeLists.txt
  example/29_batched_gemm_bias_e_permute/batched_gemm_bias_e_permute_xdl_fp16.cpp
  example/29_batched_gemm_multi_d/CMakeLists.txt
  example/29_batched_gemm_multi_d/batched_gemm_bias_xdl_fp16.cpp
  example/29_batched_gemm_multi_d/batched_gemm_xdl_fp16.cpp
  example/CMakeLists.txt
  include/ck/tensor_operation/gpu/device/device_batched_contraction_multiple_d.hpp
  include/ck/tensor_operation/gpu/device/device_batched_contraction_multiple_d_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_grouped_contraction_multiple_d.hpp
  include/ck/tensor_operation/gpu/device/device_grouped_contraction_multiple_d_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/tensor_specialization.hpp
Labels: CI Passes

#354 Move literal ""_uz & ""_zu into namespace 'ck::literals'
  example/04_gemm_add_add_fastgelu/run_gemm_add_add_fastgelu_example.inc
  library/include/ck/library/utility/literals.hpp
Labels: CI - Testing

#345 Fused attention
  CMakeLists.txt
  example/18_batched_gemm_reduce/batched_gemm_reduce_xdl_fp16.cpp
  example/24_batched_gemm_e_permute/batched_gemm_e_permute_xdl_fp16.cpp
  example/32_batched_gemm_gemm/CMakeLists.txt
  example/32_batched_gemm_gemm/batched_gemm_softmax_gemm_xdl_fp16.cpp
  example/CMakeLists.txt
  include/ck/tensor_description/tensor_descriptor.hpp
  include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops.hpp
  include/ck/tensor_operation/gpu/block/blockwise_softmax.hpp
  include/ck/tensor_operation/gpu/block/reduction_functions_blockwise.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_gemm.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_softmax_gemm.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_softmax_gemm_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_softmax_gemm_xdl_cshuffle_v1.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer.hpp
  include/ck/tensor_operation/gpu/warp/xdlops_gemm.hpp
  include/ck/utility/static_buffer.hpp
  include/ck/utility/statically_indexed_array_multi_index.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_batched_gemm.hpp
  library/include/ck/library/tensor_operation_instance/gpu/batched_gemm_softmax_gemm.hpp
  library/include/ck/library/utility/host_tensor_generator.hpp
  library/src/tensor_operation_instance/gpu/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/batched_gemm_softmax_gemm/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/batched_gemm_softmax_gemm/device_batched_gemm_softmax_gemm_xdl_cshuffle_f16_f16_f16_f16_gmk_gnk_gno_gmo_instance.cpp
  profiler/include/profile_batched_gemm_impl.hpp
  profiler/include/profile_batched_gemm_reduce_impl.hpp
  profiler/include/profile_batched_gemm_softmax_gemm_impl.hpp
  test/CMakeLists.txt
  test/batched_gemm_softmax_gemm/CMakeLists.txt
  test/batched_gemm_softmax_gemm/test_batched_gemm_softmax_gemm_fp16.cpp
  test/batched_gemm_softmax_gemm/test_batched_gemm_softmax_gemm_util.hpp
Labels: CI - Testing

#335 Gemm multiple d multiple r
  example/16_gemm_multi_d_multi_reduces/CMakeLists.txt
  example/16_gemm_multi_d_multi_reduces/gemm_add_add_mean_meansquare_xdl_fp16.cpp
  example/16_gemm_multi_d_multi_reduces/gemm_max_xdl_fp16.cpp
  example/16_gemm_multi_d_multi_reduces/gemm_mean_meansquare_xdl_fp16.cpp
  example/16_gemm_reduce/CMakeLists.txt
  example/16_gemm_reduce/gemm_reduce_xdl_max_fp16.cpp
  example/16_gemm_reduce/gemm_reduce_xdl_mean_squaremean_fp16.cpp
  example/21_gemm_layernorm/gemm_bias_relu_add_layernorm_xdl_fp16.cpp
  example/21_gemm_layernorm/gemm_layernorm_xdl_fp16.cpp
  example/CMakeLists.txt
  include/ck/tensor_operation/gpu/device/device_gemm_multiple_d_multiple_r.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_multiple_d_multiple_r_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/element/element_wise_operation.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_multiple_d_multiple_r_xdl_cshuffle.hpp
Labels: CI - Pass

#326 Skip lds of b matrix
  example/01_gemm/CMakeLists.txt
  example/01_gemm/gemm_xdl_skip_b_lds_fp16.cpp
  include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops_skip_b_lds.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl_skip_b_lds.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_skip_b_lds_v1.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer.hpp
  include/ck/utility/synchronization.hpp
Labels: CI - Pass

#351 Fused GEMM+GEMM
  example/01_gemm/gemm_xdl_skip_b_lds_fp16.cpp
  example/30_grouped_convnd_fwd_bias_relu/CMakeLists.txt
  example/30_grouped_convnd_fwd_bias_relu/README.md
  example/30_grouped_convnd_fwd_bias_relu/grouped_convnd_fwd_bias_common.hpp
  example/30_grouped_convnd_fwd_bias_relu/grouped_convnd_fwd_bias_relu_xdl_fp16.cpp
  example/30_grouped_convnd_fwd_bias_relu_add/CMakeLists.txt
  example/30_grouped_convnd_fwd_bias_relu_add/README.md
  example/30_grouped_convnd_fwd_bias_relu_add/grouped_convnd_fwd_bias_relu_add_common.hpp
  example/30_grouped_convnd_fwd_bias_relu_add/grouped_convnd_fwd_bias_relu_add_xdl_bf16.cpp
  example/30_grouped_convnd_fwd_bias_relu_add/grouped_convnd_fwd_bias_relu_add_xdl_fp16.cpp
  example/30_grouped_convnd_fwd_bias_relu_add/grouped_convnd_fwd_bias_relu_add_xdl_fp32.cpp
  example/30_grouped_convnd_fwd_bias_relu_add/grouped_convnd_fwd_bias_relu_add_xdl_int8.cpp
  example/31_batched_gemm_gemm/CMakeLists.txt
  example/31_batched_gemm_gemm/batched_gemm_gemm_xdl_fp16.cpp
  example/32_batched_gemm_softmax_gemm/CMakeLists.txt
  example/32_batched_gemm_softmax_gemm/batched_gemm_softmax_gemm_xdl_fp16.cpp
  example/CMakeLists.txt
  include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops_skip_b_lds.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_gemm_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl_skip_b_lds.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_gemm_xdl_cshuffle_v1.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_skip_b_lds_v1.hpp
  include/ck/utility/static_buffer.hpp
  library/include/ck/library/tensor_operation_instance/gpu/batched_gemm_gemm.hpp
  library/src/tensor_operation_instance/gpu/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/batched_gemm_gemm/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/batched_gemm_gemm/device_batched_gemm_gemm_xdl_cshuffle_f16_f16_f16_f16_gmk_gnk_gno_gmo_instance.cpp
  profiler/include/profile_batched_gemm_gemm_impl.hpp
  test/CMakeLists.txt
  test/batched_gemm_gemm/CMakeLists.txt
  test/batched_gemm_gemm/test_batched_gemm_gemm_fp16.cpp
  test/batched_gemm_gemm/test_batched_gemm_gemm_util.hpp
Labels: CI - Pass

#338 Change all device operations to use add_instance_library
  library/include/ck/library/utility/device_memory.hpp
  library/src/tensor_operation_instance/gpu/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/batched_gemm/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/batched_gemm_gemm/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/batched_gemm_reduce/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/batched_gemm_softmax_gemm/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/contraction_bilinear/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/contraction_scale/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/conv1d_bwd_data/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/conv1d_bwd_weight/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/conv2d_bwd_data/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/conv2d_bwd_weight/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/conv2d_fwd/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/conv2d_fwd_bias_relu/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/conv2d_fwd_bias_relu_add/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/conv3d_bwd_data/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/conv3d_bwd_weight/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/elementwise/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/gemm/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/gemm_add_add_fastgelu/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/gemm_bias_add_reduce/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/gemm_bilinear/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/gemm_reduce/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/gemm_splitk/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/grouped_conv1d_fwd/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/grouped_conv2d_fwd/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/grouped_conv3d_fwd/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/grouped_gemm/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/normalization/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/reduce/CMakeLists.txt
  library/src/utility/device_memory.cpp
Labels: CI - Testing

#357 fix build issue
  example/16_gemm_multi_d_multi_reduces/CMakeLists.txt
Labels: CI - Testing

#320 Batchnorm-forward and Batchnorm-infer Implemented using generic kernels
  client_example/03_gemm_layernorm/gemm_add_add_layernorm.cpp
  example/19_binary_elementwise/broadcast_add_2d_amn_bn.cpp
  example/19_binary_elementwise/broadcast_add_3d_am_bmnk.cpp
  example/19_binary_elementwise/elementwise_add_1d.cpp
  example/19_binary_elementwise/elementwise_add_4d.cpp
  example/21_gemm_layernorm/gemm_bias_relu_add_layernorm_xdl_fp16.cpp
  example/21_gemm_layernorm/gemm_layernorm_xdl_fp16.cpp
  example/33_multiple_reduce/CMakeLists.txt
  example/33_multiple_reduce/README.md
  example/33_multiple_reduce/dual_reduce_common.hpp
  example/33_multiple_reduce/dual_reduce_multiblock.cpp
  example/33_multiple_reduce/dual_reduce_threadwise.cpp
  example/34_batchnorm/CMakeLists.txt
  example/34_batchnorm/README.md
  example/34_batchnorm/batchnorm_common.hpp
  example/34_batchnorm/batchnorm_forward_impl.hpp
  example/34_batchnorm/batchnorm_forward_nhwc.cpp
  example/34_batchnorm/batchnorm_infer_impl.hpp
  example/34_batchnorm/batchnorm_infer_nhwc.cpp
  example/CMakeLists.txt
  include/ck/tensor_operation/gpu/device/device_5ary_elementwise.hpp
  include/ck/tensor_operation/gpu/device/device_batchnorm_forward.hpp
  include/ck/tensor_operation/gpu/device/device_batchnorm_infer.hpp
  include/ck/tensor_operation/gpu/device/device_binary_elementwise.hpp
  include/ck/tensor_operation/gpu/device/device_cgemm_4gemm_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_conv2d_backward_weight_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_convnd_bwd_weight_nwc_kxc_nwk_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_elementwise.hpp
  include/ck/tensor_operation/gpu/device/device_elementwise_base.hpp
  include/ck/tensor_operation/gpu/device/device_multiple_reduce.hpp
  include/ck/tensor_operation/gpu/device/device_multiple_reduce_multiblock.hpp
  include/ck/tensor_operation/gpu/device/device_multiple_reduce_threadwise.hpp
  include/ck/tensor_operation/gpu/device/device_reduce_common.hpp
  include/ck/tensor_operation/gpu/device/device_unary_elementwise.hpp
  include/ck/tensor_operation/gpu/element/element_wise_operation.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_2d_multiple_reduction_multiblock.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_2d_multiple_reduction_threadwise.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_5ary_Elementwise_1d.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_binary_elementwise_1d.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_elementwise_1d.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_set_multiple_buffer_value.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_unary_elementwise_1d.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_batchnorm_forward_nhwc_c.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_batchnorm_infer_nhwc_c.hpp
  library/include/ck/library/tensor_operation_instance/gpu/device_elementwise_instance.hpp
  library/include/ck/library/utility/host_tensor_generator.hpp
  library/src/tensor_operation_instance/gpu/elementwise/device_normalize_instance.cpp
Labels: CI - Pass, merge conflict

#379 layernorm external api
  .gitignore
  client_example/05_layernorm/CMakeLists.txt
  client_example/05_layernorm/layernorm2d.cpp
  client_example/CMakeLists.txt
  library/include/ck/library/tensor_operation_instance/gpu/layernorm.hpp
Labels: CI - Testing

#372 Add int4 reduction examples
  example/12_reduce/reduce_blockwise.cpp
  example/12_reduce/reduce_blockwise_impl.hpp
Labels: CI - Failed

#374 More int4 tests.
  include/ck/utility/data_type.hpp
  test/data_type/int4.cpp
Labels: CI - Pass

#385 Padding for attention: bmm+scale+softmax+bmm kernel
  example/32_batched_gemm_scale_softmax_gemm/CMakeLists.txt
  example/32_batched_gemm_scale_softmax_gemm/padded_batched_gemm_scale_softmax_gemm_xdl_fp16.cpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_softmax_gemm_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/element/unary_element_wise_operation.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_softmax_gemm_xdl_cshuffle_v1.hpp
  include/ck/utility/data_type.hpp
Labels: CI - Pass

#393 conv+conv (1x1 only) example using gemm+gemm
  example/09_convnd_fwd/convnd_fwd_xdl_fp16.cpp
  example/30_grouped_convnd_fwd_bias_relu_add/grouped_convnd_fwd_bias_relu_add_xdl_fp16.cpp
  example/41_grouped_conv_conv_fwd/CMakeLists.txt
  example/41_grouped_conv_conv_fwd/grouped_conv_conv_fwd_common.hpp
  example/41_grouped_conv_conv_fwd/grouped_conv_conv_fwd_xdl_fp16.cpp
  example/CMakeLists.txt
  include/ck/tensor_operation/gpu/device/device_batched_gemm_gemm_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_multi_d_xdl.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_multiple_d_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_grouped_conv_fwd_multiple_d.hpp
  include/ck/tensor_operation/gpu/device/device_grouped_conv_fwd_multiple_d_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/matrix_padder.hpp
  include/ck/tensor_operation/operator_transform/transform_conv_fwd_to_gemm.hpp
  library/include/ck/library/utility/convolution_parameter.hpp
Labels: CI - Pass
