Repository ROCm/composable_kernel, pull requests merged in 2022-05, with the labels that each got.

#175 Code refactor
  example/01_gemm/gemm_xdl_bf16.cpp
  example/01_gemm/gemm_xdl_fp16.cpp
  example/01_gemm/gemm_xdl_int8.cpp
  example/14_gemm_xdl_requant_relu_requant/gemm_xdl_requant_relu_requant_int8.cpp
  include/ck/config.hpp
  include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops.hpp
  include/ck/tensor_operation/gpu/block/blockwise_tensor_slice_transfer_v5r1.hpp
  include/ck/tensor_operation/gpu/block/thread_group_tensor_slice_transfer_v4r1.hpp
  include/ck/tensor_operation/gpu/block/thread_group_tensor_slice_transfer_v6r1.hpp
  include/ck/tensor_operation/gpu/block/thread_group_tensor_slice_transfer_v6r2.hpp
  include/ck/tensor_operation/gpu/block/thread_group_tensor_slice_transfer_v6r3.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_reduce_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_xdl.hpp
  include/ck/tensor_operation/gpu/device/device_conv2d_bwd_data_xdl_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_conv2d_fwd_xdl_c_shuffle_bias_activation_add_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_conv2d_fwd_xdl_c_shuffle_bias_activation_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_conv2d_fwd_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_conv2d_fwd_xdl_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_convnd_bwd_data_xdl_ndhwc_kzyxc_ndhwk.hpp
  include/ck/tensor_operation/gpu/device/device_convnd_fwd_xdl_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_reduce_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl_c_shuffle.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl_c_shuffle_bias_2d.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl_c_shuffle_bias_activation.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl_c_shuffle_bias_activation_add.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_grouped_gemm_xdl.hpp
  include/ck/tensor_operation/gpu/element/element_wise_operation.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_pipeline_v1.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_reduce_xdl_cshuffle_v1.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdl_cshuffle_v1.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v2r3.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v2r4.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v2r4r2.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v3r1.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v3r2.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v3r3.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v6r1.hpp
  include/ck/utility/amd_xdlops.hpp
  include/ck/utility/common_header.hpp
  include/ck/utility/get_id.hpp
  include/ck/utility/thread_group.hpp
  include/ck/utility/tuple.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_gemm.hpp
  library/src/tensor_operation_instance/gpu/gemm/device_gemm_xdl_c_shuffle_2_stage_f16_f16_f16_mk_nk_mn_instance.cpp
  profiler/include/profile_gemm_impl.hpp
  test/gemm/gemm_bf16.cpp
  test/gemm/gemm_fp16.cpp
  test/gemm/gemm_fp32.cpp
  test/gemm/gemm_int8.cpp
Labels: CI Passes

#212 Resolution of issue #153: Add compiler warning on comparing int and size_t
  cmake/EnableCompilerWarnings.cmake
  example/12_reduce/reduce_blockwise.cpp
  example/13_pool2d_fwd/pool2d_fwd.cpp
  example/15_grouped_gemm/grouped_gemm_xdl_fp16.cpp
  include/ck/tensor_description/tensor_descriptor_helper.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_reduce_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_xdl.hpp
  include/ck/tensor_operation/gpu/device/device_conv2d_bwd_data_xdl_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_convnd_bwd_data_xdl_ndhwc_kzyxc_ndhwk.hpp
  include/ck/tensor_operation/gpu/device/device_convnd_fwd_xdl_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_grouped_gemm_xdl.hpp
  include/ck/utility/number.hpp
  include/ck/utility/static_buffer.hpp
  library/include/ck/library/host_tensor/host_reduction.hpp
  library/include/ck/library/host_tensor/host_tensor.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_conv_backward_weight.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_conv_bwd_data.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_conv_fwd.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_conv_fwd_bias_activation.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_conv_fwd_bias_activation_add.hpp
  library/src/host_tensor/host_tensor.cpp
  library/src/utility/conv_fwd_util.cpp
  profiler/include/profile_convnd_bwd_data_impl.hpp
  profiler/include/profile_grouped_gemm_impl.hpp
  profiler/src/profile_reduce.cpp
  test/gemm_split_k/gemm_split_k.cpp
  test/grouped_gemm/grouped_gemm_fp16.cpp
  test/reduce/reduce_no_index.cpp
  test/reduce/reduce_util.hpp
  test/reduce/reduce_with_index.cpp
Labels: code quality, CI Passes

#224 Post PR183 review fixes.
  cmake/googletest.cmake
  example/06_conv2d_fwd_bias_relu/CMakeLists.txt
  example/06_conv2d_fwd_bias_relu/conv2d_fwd_xdl_bias_relu.cpp
  example/07_conv2d_fwd_bias_relu_add/CMakeLists.txt
  example/07_conv2d_fwd_bias_relu_add/conv2d_fwd_xdl_bias_relu_add.cpp
  example/09_convnd_fwd/CMakeLists.txt
  example/09_convnd_fwd/convnd_fwd_xdl.cpp
  example/09_convnd_fwd/convnd_fwd_xdl_fp16.cpp
  example/09_convnd_fwd/convnd_fwd_xdl_int8.cpp
  example/10_conv2d_bwd_data/CMakeLists.txt
  example/11_conv2d_bwd_weight/CMakeLists.txt
  example/17_convnd_bwd_data_xdl/CMakeLists.txt
  example/17_convnd_bwd_data_xdl/convnd_bwd_data_xdl.cpp
  include/ck/tensor_operation/gpu/device/device_conv3d_fwd_naive_ndhwc_kzyxc_ndhwk.hpp
  library/include/ck/library/utility/conv_util.hpp
  library/src/utility/CMakeLists.txt
  library/src/utility/conv_util.cpp
  profiler/CMakeLists.txt
  profiler/include/profile_convnd_bwd_data_impl.hpp
  profiler/src/profile_convnd_bwd_data.cpp
  profiler/src/profile_convnd_fwd.cpp
  test/CMakeLists.txt
  test/conv2d_bwd_weight/CMakeLists.txt
  test/conv2d_bwd_weight/conv2d_bwd_weight.cpp
  test/conv_util/CMakeLists.txt
  test/conv_util/conv_util.cpp
  test/convnd_bwd_data/CMakeLists.txt
  test/convnd_bwd_data/convnd_bwd_data.cpp
  test/convnd_fwd/CMakeLists.txt
  test/convnd_fwd/conv1d_fwd.cpp
  test/convnd_fwd/conv2d_fwd.cpp
  test/convnd_fwd/conv3d_fwd.cpp
  test/convnd_fwd/conv_util.hpp
  test/reference_conv_fwd/CMakeLists.txt
  test/reference_conv_fwd/reference_conv_fwd.cpp
Labels: code quality

#184 Manual control of MAC cluster for improved interwave performance
  include/ck/config.hpp
  include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_reduce_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_reduce_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_pipeline_v1.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_reduce_xdl_cshuffle_v1.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdl_cshuffle_v1.hpp
Labels: CI Passes

#190 [Perf][Bwd-weights]Lds re-layout to avoid ds read/write bank conflict and balance ds ops with address calculations
  include/ck/tensor_operation/gpu/device/device_conv2d_backward_weight_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_bwd_weight.hpp
Labels: CI Passes

#245 remove unused conv bwd data profiler header and cpp
  profiler/include/profile_conv_bwd_data_impl.hpp
  profiler/src/profile_conv_bwd_data.cpp
Labels: CI Passes

#202 [conv bwd-weight]Binding gemm k1 to conv n
  include/ck/tensor_operation/gpu/device/device_conv2d_backward_weight_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_bwd_weight.hpp
Labels: CI Passes

#235 Refactor block to C tile map
  include/ck/tensor_operation/gpu/device/device_batched_gemm_reduce_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_batched_gemm_xdl.hpp
  include/ck/tensor_operation/gpu/device/device_conv2d_backward_weight_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_conv2d_bwd_data_xdl_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_conv2d_fwd_xdl_c_shuffle_bias_activation_add_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_conv2d_fwd_xdl_c_shuffle_bias_activation_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_conv2d_fwd_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_conv2d_fwd_xdl_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_conv3d_fwd_xdl_ndhwc_kzyxc_ndhwk.hpp
  include/ck/tensor_operation/gpu/device/device_convnd_bwd_data_xdl_ndhwc_kzyxc_ndhwk.hpp
  include/ck/tensor_operation/gpu/device/device_convnd_fwd_xdl_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_reduce_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl_c_shuffle_bias_2d.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl_c_shuffle_bias_activation.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl_c_shuffle_bias_activation_add.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl_splitk.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl_splitk_c_shuffle.hpp
  include/ck/tensor_operation/gpu/device/device_grouped_gemm_xdl.hpp
  include/ck/tensor_operation/gpu/grid/block_to_ctile_map.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_reduce_xdl_cshuffle_v1.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdl_cshuffle_v1.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v2r3.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v2r4.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v2r4r2.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v3r1.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v3r2.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v3r3.hpp
  include/ck/utility/statically_indexed_array_multi_index.hpp
  test/CMakeLists.txt
  test/block_to_ctile_map/CMakeLists.txt
  test/block_to_ctile_map/test_block_to_ctile_map.cpp
Labels: CI Passes

#244 example of conv bwd weight 1d/2d/3d fp32/fp16/bf16 xdl
  example/20_convnd_bwd_weight_xdl/CMakeLists.txt
  example/20_convnd_bwd_weight_xdl/convnd_bwd_weight_xdl.cpp
  example/CMakeLists.txt
  include/ck/tensor_operation/gpu/device/convolution_backward_weight_specialization.hpp
  include/ck/tensor_operation/gpu/device/device_convnd_backward_weight_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_conv_backward_weight.hpp
Labels: CI Passes

#255 minor fix for recent PR
  include/ck/utility/dynamic_buffer.hpp
  profiler/src/profiler.cpp
Labels: code quality

#258 Fixing conv bug
  example/09_convnd_fwd/convnd_fwd_xdl_fp16.cpp
  example/09_convnd_fwd/convnd_fwd_xdl_fp32.cpp
  example/09_convnd_fwd/convnd_fwd_xdl_int8.cpp
  example/17_convnd_bwd_data_xdl/convnd_bwd_data_xdl.cpp
  example/20_convnd_bwd_weight_xdl/convnd_bwd_weight_xdl.cpp
  include/ck/tensor_operation/gpu/device/device_conv2d_fwd_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_convnd_fwd_xdl_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v3r1.hpp
Labels: bug

#260 Minor fix for recent PR
  example/01_gemm/CMakeLists.txt
  example/01_gemm/gemm_dl_fp16.cpp
  example/01_gemm/gemm_dl_fp32.cpp
  example/01_gemm/gemm_dl_int8.cpp
  example/01_gemm/gemm_xdl_bf16.cpp
  example/01_gemm/gemm_xdl_fp16.cpp
  example/01_gemm/gemm_xdl_fp64.cpp
  example/01_gemm/gemm_xdl_int8.cpp
  example/09_convnd_fwd/CMakeLists.txt
  include/ck/tensor_operation/gpu/device/device_convnd_fwd_xdl_nhwc_kyxc_nhwk.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_dl.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_xdl.hpp
Labels: code quality

#230 Multi-kernel CGEMM
  example/19_binary_elementwise/broadcast_add_2d_amn_bn.cpp
  example/19_binary_elementwise/broadcast_add_3d_am_bmnk.cpp
  example/19_binary_elementwise/elementwise_add_1d.cpp
  example/19_binary_elementwise/elementwise_add_4d.cpp
  example/22_cgemm/CMakeLists.txt
  example/22_cgemm/cgemm_xdl_fp16.cpp
  example/CMakeLists.txt
  include/ck/tensor_operation/gpu/device/device_cgemm.hpp
  include/ck/tensor_operation/gpu/device/device_cgemm_4gemm_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_dl.hpp
  include/ck/tensor_operation/gpu/element/binary_element_wise_operation.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_cgemm.hpp
Labels: CI Passes

#232 Pass gemm_descs for grouped gemm via __constant__ buff
  example/15_grouped_gemm/grouped_gemm_xdl_fp16.cpp
  include/ck/tensor_operation/gpu/device/device_base.hpp
  include/ck/tensor_operation/gpu/device/device_grouped_gemm_xdl.hpp
  test/grouped_gemm/grouped_gemm_fp16.cpp
Labels: CI Passes
