Repository ROCm/composable_kernel, pull requests merged in 2023-04, with the labels that each got.

#665 Revert "simplify karg in device/grid of split-k op (#644)"
  include/ck/tensor_operation/gpu/device/impl/device_gemm_xdl_splitk_c_shuffle.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v2r4r2.hpp
  library/src/tensor_operation_instance/gpu/gemm_splitk/device_gemm_xdl_splitk_f16_f16_f16_mk_kn_mn_instance.cpp
Labels: urgency_blocker

#670 [gtest] suppress unsafe buffer warn
  cmake/googletest.cmake
Labels: compiler bug, urgency_high, quality

#680 [Navi3x] add vector load check
  include/ck/tensor_operation/gpu/device/impl/device_gemm_multiple_d_wmma_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/impl/device_gemm_wmma.hpp
Labels: bug
