Repository ROCm/composable_kernel, pull requests merged in 2023-12, with the labels that each got.

#1077 [SWDEV-435347] disable instances failed with mainlien compiler
  library/include/ck/library/tensor_operation_instance/gpu/grouped_convolution_forward_scaleadd_ab.hpp
  library/src/tensor_operation_instance/gpu/grouped_conv3d_fwd_scaleadd_ab/xdl/device_grouped_conv3d_fwd_xdl_scaleadd_ab_ndhwgc_gkzyxc_ndhwgk_bf16_instance.cpp
Labels: compiler bug, urgency_blocker

#1057 Standardize documentation for ReadtheDocs
  .github/dependabot.yml
  .gitignore
  .readthedocs.yaml
  docs/conf.py
  docs/doxygen/Doxyfile
  docs/sphinx/_toc.yml.in
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation, ci:docs-only

#1085 [Doc][Werror] Fix security alerts and sync with MIOpen
  docs/sphinx/requirements.txt
  include/ck/tensor_operation/gpu/grid/gridwise_tensor_rearrange.hpp
Labels: urgency_low, quality

#1082 enable compilation of INSTANCES_ONLY for Windows
  .gitignore
  CMakeLists.txt
  cmake/getopt.cmake
  cmake/googletest.cmake
  cmake/gtest.cmake
  include/ck/tensor_operation/gpu/element/unary_element_wise_operation.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_elementwise_layernorm_welford_variance.hpp
  include/ck/tensor_operation/gpu/warp/wmma_gemm.hpp
  library/src/tensor_operation_instance/gpu/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/softmax/CMakeLists.txt
  library/src/utility/CMakeLists.txt
  profiler/src/CMakeLists.txt
  test/CMakeLists.txt
Labels: windows

#1109 Fix results verify in test_tensor
  test/wrapper/test_tensor.cpp
Labels: bug, urgency_blocker
