Repository ROCm/composable_kernel, pull requests merged in 2024-07, with the labels that each got.

#1372 Fix issue with multiple targets and remove smfmac tests from unsupported test targets
  Jenkinsfile
  client_example/25_wrapper/wrapper_basic_gemm.cpp
  client_example/25_wrapper/wrapper_optimized_gemm.cpp
  example/02_gemm_bilinear/gemm_bilinear_wmma_fp16.cpp
  example/02_gemm_bilinear/gemm_bilinear_wmma_int8.cpp
  example/30_grouped_conv_fwd_multiple_d/grouped_conv_fwd_bias_relu_add_wmma_fp16.cpp
  example/30_grouped_conv_fwd_multiple_d/grouped_conv_fwd_bias_relu_add_wmma_int8.cpp
  example/32_batched_gemm_scale_softmax_gemm/batched_gemm_lower_triangle_scale_softmax_gemm_permute_wmma_fp16.cpp
  example/32_batched_gemm_scale_softmax_gemm/batched_gemm_scale_softmax_gemm_permute_wmma_fp16.cpp
  example/32_batched_gemm_scale_softmax_gemm/cross_attention_forward_wmma_fp16.cpp
  example/32_batched_gemm_scale_softmax_gemm/grouped_query_attention_forward_wmma_fp16.cpp
  example/32_batched_gemm_scale_softmax_gemm/multi_query_attention_forward_wmma_fp16.cpp
  example/32_batched_gemm_scale_softmax_gemm/self_attention_forward_wmma_fp16.cpp
  example/38_grouped_conv_bwd_data_multiple_d/grouped_conv_bwd_data_wmma_fp16.cpp
  include/ck/tensor_operation/gpu/device/impl/device_grouped_conv_bwd_weight_two_stage_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/impl/device_grouped_conv_fwd_multiple_abd_xdl_cshuffle_v3.hpp
  include/ck/utility/amd_smfmac.hpp
  test/CMakeLists.txt
  test/grouped_convnd_bwd_data/CMakeLists.txt
  test/grouped_convnd_bwd_data/test_grouped_convnd_bwd_data_interface_wmma.cpp
  test/grouped_convnd_bwd_weight/CMakeLists.txt
  test/grouped_convnd_bwd_weight/test_grouped_convnd_bwd_weight_interface_wmma.cpp
  test/grouped_convnd_fwd/CMakeLists.txt
  test/wmma_op/wmma_op_util.hpp
Labels: bug, CI - Pass, urgency_blocker

#1376 Fix the cmake logic when building with INSTANCES_ONLY=ON.
  example/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/CMakeLists.txt
  test/CMakeLists.txt
Labels: CI - Pass

#1378 Update changelog release headers
  .github/CODEOWNERS
  CHANGELOG.md
Labels: documentation, ci:docs-only

#1382 Support access per groups and filter3x3 in grouped conv fwd
  include/ck/tensor_operation/gpu/device/convolution_forward_specialization.hpp
  include/ck/tensor_operation/gpu/device/impl/device_grouped_conv_bwd_weight_two_stage_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/impl/device_grouped_conv_fwd_multiple_abd_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/impl/device_grouped_conv_utils.hpp
  include/ck/tensor_operation/operator_transform/transform_conv_bwd_weight_to_gemm_v2.hpp
  include/ck/tensor_operation/operator_transform/transform_conv_fwd_to_gemm.hpp
  library/include/ck/library/tensor_operation_instance/gpu/grouped_conv_bwd_weight/device_grouped_conv_bwd_weight_two_stage_xdl_instance.hpp
  library/include/ck/library/tensor_operation_instance/gpu/grouped_conv_fwd/device_grouped_conv_fwd_xdl_merged_groups_instance.hpp
  library/include/ck/library/tensor_operation_instance/gpu/grouped_convolution_forward.hpp
  library/include/ck/library/tensor_operation_instance/gpu/grouped_convolution_forward_xdl_merged_groups.inc
  library/src/tensor_operation_instance/gpu/grouped_conv2d_fwd/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/grouped_conv2d_fwd/xdl/merged_groups/device_grouped_conv2d_fwd_xdl_merged_groups_nhwgc_gkyxc_nhwgk_bf16_instance.cpp
  library/src/tensor_operation_instance/gpu/grouped_conv2d_fwd/xdl/merged_groups/device_grouped_conv2d_fwd_xdl_merged_groups_nhwgc_gkyxc_nhwgk_f16_instance.cpp
  library/src/tensor_operation_instance/gpu/grouped_conv2d_fwd/xdl/merged_groups/device_grouped_conv2d_fwd_xdl_merged_groups_nhwgc_gkyxc_nhwgk_f32_instance.cpp
  library/src/tensor_operation_instance/gpu/grouped_conv3d_fwd/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/grouped_conv3d_fwd/xdl/merged_groups/device_grouped_conv3d_fwd_xdl_merged_groups_ndhwgc_gkzyxc_ndhwgk_bf16_instance.cpp
  library/src/tensor_operation_instance/gpu/grouped_conv3d_fwd/xdl/merged_groups/device_grouped_conv3d_fwd_xdl_merged_groups_ndhwgc_gkzyxc_ndhwgk_f16_instance.cpp
  library/src/tensor_operation_instance/gpu/grouped_conv3d_fwd/xdl/merged_groups/device_grouped_conv3d_fwd_xdl_merged_groups_ndhwgc_gkzyxc_ndhwgk_f32_instance.cpp
  test/grouped_convnd_fwd/test_grouped_convnd_fwd.cpp
Labels: enhancement, CI - Pass

#1388 [SWDEV_466907] Disable failed instance in rocm6.2 rel
  library/src/tensor_operation_instance/gpu/gemm_universal/device_gemm_xdl_universal_f16_f8_f16/device_gemm_xdl_universal_f16_f8_f16_mk_kn_mn.hpp
  profiler/include/profiler/profile_gemm_universal_impl.hpp
Labels: CI - Pass

#1412 Adding more instances of grouped convolution 3d forward for FP8 with ConvScale+Bias element-wise operation.
  client_example/24_grouped_conv_activation/CMakeLists.txt
  client_example/24_grouped_conv_activation/grouped_convnd_fwd_convscale_add/common.hpp
  client_example/24_grouped_conv_activation/grouped_convnd_fwd_convscale_add/conv3d_fwd_convscale_add_fp8.cpp
  example/62_convnd_activ/CMakeLists.txt
  example/62_convnd_activ/convscale_add/CMakeLists.txt
  example/62_convnd_activ/convscale_add/convnd_fwd_convscale_add_common.hpp
  example/62_convnd_activ/convscale_add/convnd_fwd_xdl_convscale_add_fp8.cpp
  example/62_convnd_activ/convscale_add/run_convnd_fwd_convscale_add_example.inc
  include/ck/tensor_operation/gpu/element/binary_element_wise_operation.hpp
  library/include/ck/library/tensor_operation_instance/gpu/grouped_conv_fwd/device_grouped_conv_fwd_xdl_binary_outelementop_instance.hpp
  library/include/ck/library/tensor_operation_instance/gpu/grouped_convolution_forward_convscale_add.hpp
  library/src/tensor_operation_instance/gpu/grouped_conv3d_fwd_convscale_add/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/grouped_conv3d_fwd_convscale_add/xdl/device_grouped_conv3d_fwd_xdl_convscale_add_ndhwgc_gkzyxc_ndhwgk_f8_instance.cpp
Labels: CI - Pass

#1423 Update documentation requirements
  docs/sphinx/requirements.txt
Labels: documentation, ci:docs-only
