Repository ROCm/composable_kernel, pull requests merged in 2024-04, with the labels that each got.

#1217 Introduce combined elementwise ops
  example/44_elementwise_permute/CMakeLists.txt
  example/44_elementwise_permute/elementwise_binary_4D_fp16.cpp
  example/44_elementwise_permute/elementwise_permute.cpp
  example/44_elementwise_permute/elementwise_permute_3d.cpp
  example/44_elementwise_permute/elementwise_permute_4D_fp16.cpp
  example/44_elementwise_permute/elementwise_permute_4D_fp16_2d.cpp
  example/44_elementwise_permute/elementwise_permute_4D_fp16_col.cpp
  example/44_elementwise_permute/elementwise_permute_4D_fp16_row.cpp
  example/44_elementwise_permute/elementwise_permute_4D_fp32_col.cpp
  example/44_elementwise_permute/elementwise_permute_4D_fp32_row.cpp
  example/44_elementwise_permute/elementwise_trinary_4D_fp16.cpp
  include/ck/tensor_operation/gpu/element/binary_element_wise_operation.hpp
  include/ck/tensor_operation/gpu/element/combined_element_wise_operation.hpp
  include/ck/tensor_operation/gpu/element/unary_element_wise_operation.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_elementwise_dynamic_vector_dims.hpp
  include/ck/utility/math_v2.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_elementwise.hpp
  profiler/include/profiler/profile_permute_scale_impl.hpp
Labels: CI - Pass

#1225 Add a conv fwd fp16 comp fp8 example
  example/09_convnd_fwd/CMakeLists.txt
  example/09_convnd_fwd/convnd_fwd_xdl_fp16_comp_fp8.cpp
Labels: CI - Pass

#1226 flush cache for universal gemm
  example/01_gemm/run_gemm_example_v2.inc
  include/ck/host_utility/flush_cache.hpp
  include/ck/stream_config.hpp
  include/ck/tensor_operation/gpu/device/impl/device_gemm_xdl_cshuffle_v3.hpp
  include/ck/utility/flush_icache.hpp
  profiler/include/profiler/profile_gemm_universal_impl.hpp
  profiler/src/profile_gemm_universal.cpp
Labels: enhancement

#978 Added Multi_ABD support into Gemm and GroupedGemmFixedNK
  client_example/30_gemm_multi_abd/CMakeLists.txt
  client_example/30_gemm_multi_abd/gemm_bias_fastgelu_xdl_bf16_i8.cpp
  client_example/30_gemm_multi_abd/gemm_bias_xdl_bf16_i8.cpp
  client_example/30_gemm_multi_abd/gemm_xdl_bf16_i8.cpp
  client_example/30_gemm_multi_abd/gemm_xdl_gelu_bf16_i8.cpp
  client_example/31_grouped_gemm_multi_abd/CMakeLists.txt
  client_example/31_grouped_gemm_multi_abd/grouped_gemm_bias_fastgelu_xdl_bf16_i8.cpp
  client_example/31_grouped_gemm_multi_abd/grouped_gemm_fastgelu_xdl_bf16_i8.cpp
  example/59_grouped_gemm_multi_ABD/CMakeLists.txt
  example/59_grouped_gemm_multi_ABD/grouped_gemm_multi_abd_xdl_fixed_nk_bias_bf16_i8.cpp
  example/59_grouped_gemm_multi_ABD/grouped_gemm_multi_abd_xdl_fixed_nk_bias_fp16.cpp
  example/60_gemm_multi_ABD/CMakeLists.txt
  example/60_gemm_multi_ABD/gemm_multi_ABD_xdl_bf16_i8.cpp
  example/60_gemm_multi_ABD/gemm_multi_ABD_xdl_fp16.cpp
  example/61_contraction_multi_ABD/contraction_multi_ABD_xdl_fp16.cpp
  include/ck/tensor_operation/gpu/device/device_grouped_gemm_multi_abd.hpp
  include/ck/tensor_operation/gpu/device/device_grouped_gemm_multi_abd_fixed_nk.hpp
  include/ck/tensor_operation/gpu/device/impl/device_contraction_multiple_abd_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/impl/device_gemm_multiple_abd_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/device/impl/device_grouped_gemm_multi_abd_xdl_fixed_nk.hpp
  include/ck/tensor_operation/gpu/device/impl/device_reduce_threadwise.hpp
  include/ck/tensor_operation/gpu/element/binary_element_wise_operation.hpp
  include/ck/tensor_operation/gpu/element/combined_element_wise_operation.hpp
  include/ck/tensor_operation/gpu/element/unary_element_wise_operation.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_multiple_abd_xdl_cshuffle.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_util.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v3r1.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v7r2.hpp
  library/include/ck/library/tensor_operation_instance/gpu/gemm_multi_abd.hpp
  library/include/ck/library/tensor_operation_instance/gpu/grouped_gemm_multi_abd_fixed_nk.hpp
  library/src/tensor_operation_instance/gpu/gemm_multi_abd/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/gemm_multi_abd/device_gemm_xdl_multi_abd_bf16_i8_bf16_km_kn_mn_common.hpp
  library/src/tensor_operation_instance/gpu/gemm_multi_abd/device_gemm_xdl_multi_abd_bf16_i8_bf16_mk_kn_mn_common.hpp
  library/src/tensor_operation_instance/gpu/gemm_multi_abd/device_gemm_xdl_multi_abd_bf16_i8_bf16_mk_nk_mn_common.hpp
  library/src/tensor_operation_instance/gpu/gemm_multi_abd/device_gemm_xdl_multi_abd_bias_gelu_bf16_i8_bf16_km_kn_mn_v1_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_multi_abd/device_gemm_xdl_multi_abd_bias_gelu_bf16_i8_bf16_mk_kn_mn_v1_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_multi_abd/device_gemm_xdl_multi_abd_bias_gelu_bf16_i8_bf16_mk_nk_mn_v1_instance.cpp
  library/src/tensor_operation_instance/gpu/grouped_gemm_fixed_nk_multi_abd/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/grouped_gemm_fixed_nk_multi_abd/device_grouped_gemm_xdl_fixed_nk_bf16_i8_bf16_km_kn_mn_common.hpp
  library/src/tensor_operation_instance/gpu/grouped_gemm_fixed_nk_multi_abd/device_grouped_gemm_xdl_fixed_nk_bf16_i8_bf16_mk_kn_mn_common.hpp
  library/src/tensor_operation_instance/gpu/grouped_gemm_fixed_nk_multi_abd/device_grouped_gemm_xdl_fixed_nk_bf16_i8_bf16_mk_nk_mn_common.hpp
  library/src/tensor_operation_instance/gpu/grouped_gemm_fixed_nk_multi_abd/device_grouped_gemm_xdl_fixed_nk_bias_gelu_bf16_i8_bf16_km_kn_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/grouped_gemm_fixed_nk_multi_abd/device_grouped_gemm_xdl_fixed_nk_bias_gelu_bf16_i8_bf16_mk_kn_mn_instance.cpp
  library/src/tensor_operation_instance/gpu/grouped_gemm_fixed_nk_multi_abd/device_grouped_gemm_xdl_fixed_nk_bias_gelu_bf16_i8_bf16_mk_nk_mn_instance.cpp
Labels: CI - Pass

#1244 docs: fix broken contributing link
  docs/index.rst
Labels: noCI, ci:docs-only

#1245 docs: fix broken contributing link (#1244)
  docs/index.rst
Labels: noCI, ci:docs-only

#1259 Add ConvInvscale element-wise op
  include/ck/tensor_operation/gpu/element/element_wise_operation.hpp
Labels: CI - Pass
