Repository ROCm/composable_kernel, pull requests merged in 2025-04, with the labels that each got.

#1879 f8/bf16 GEMM Stream-K
  CHANGELOG.md
  example/01_gemm/CMakeLists.txt
  example/01_gemm/gemm_xdl_fp16_fp8_streamk_v3.cpp
  library/include/ck/library/tensor_operation_instance/gpu/gemm_universal_streamk.hpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_bf16_bf16_bf16/device_gemm_xdl_universal_streamk_bf16_bf16_bf16_mk_nk_mn.hpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_bf16_bf16_bf16/device_gemm_xdl_universal_streamk_bf16_bf16_bf16_mk_nk_mn_comp_mnkpadding_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_bf16_bf16_bf16/device_gemm_xdl_universal_streamk_bf16_bf16_bf16_mk_nk_mn_comp_mnpadding_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_bf16_bf16_bf16/device_gemm_xdl_universal_streamk_bf16_bf16_bf16_mk_nk_mn_mem_v1_mnkpadding_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_bf16_bf16_bf16/device_gemm_xdl_universal_streamk_bf16_bf16_bf16_mk_nk_mn_mem_v2_mnkpadding_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_kn_mn.hpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_kn_mn_comp_default_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_kn_mn_comp_kpadding_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_kn_mn_comp_nkpadding_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_kn_mn_mem_v1_default_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_kn_mn_mem_v1_kpadding_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_kn_mn_mem_v1_nkpadding_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_kn_mn_mem_v2_default_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_kn_mn_mem_v2_kpadding_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_kn_mn_mem_v2_nkpadding_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_nk_mn.hpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_nk_mn_comp_default_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_nk_mn_comp_kpadding_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_nk_mn_mem_v1_default_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_nk_mn_mem_v1_kpadding_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_nk_mn_mem_v2_default_instance.cpp
  library/src/tensor_operation_instance/gpu/gemm_universal_streamk/device_gemm_xdl_universal_streamk_f8_f8_bf16/device_gemm_xdl_universal_streamk_f8_f8_bf16_mk_nk_mn_mem_v2_kpadding_instance.cpp
  profiler/include/profiler/profile_gemm_universal_streamk_impl.hpp
  profiler/src/profile_gemm_universal_streamk.cpp
  test/CMakeLists.txt
  test/gemm_universal_streamk/CMakeLists.txt
  test/gemm_universal_streamk/test_gemm_universal_streamk_ut_cases_bf16.inc
  test/gemm_universal_streamk/test_gemm_universal_streamk_ut_cases_fp16.inc
  test/gemm_universal_streamk/test_gemm_universal_streamk_ut_cases_fp8.inc
  test/gemm_universal_streamk/test_gemm_universal_streamk_util.hpp
  test/gemm_universal_streamk/test_gemm_universal_streamk_xdl_bf16.cpp
  test/gemm_universal_streamk/test_gemm_universal_streamk_xdl_fp16.cpp
  test/gemm_universal_streamk/test_gemm_universal_streamk_xdl_fp8.cpp
Labels: CI - Pass

#2005 add a fast compilation path for static for (0..N)
  include/ck/utility/functional2.hpp
  include/ck_tile/core/utility/functional.hpp
Labels: compilation time

#2014 Basic docs for universal gemm & ck-tile gemm.
  include/ck/tensor_operation/gpu/device/impl/device_gemm_xdl_cshuffle_v3.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdl_cshuffle_v3.hpp
  include/ck_tile/ops/gemm/kernel/gemm_kernel.hpp
Labels: documentation

#2043 simplify generate_tuple
  include/ck/utility/sequence.hpp
  include/ck/utility/tuple_helper.hpp
  include/ck_tile/core/container/tuple.hpp
Labels: compilation time

#2063 fixed broken github link
  docs/index.rst
Labels: documentation, ci:docs-only

#2036 add preshuffle gemm fp16
  example/65_gemm_multiply_multiply/CMakeLists.txt
  example/65_gemm_multiply_multiply/gemm_multiply_multiply_xdl_fp16_bpreshuffle.cpp
Labels: CI - Pass

#2026 Moe gemm activation
  example/65_gemm_multiply_multiply/CMakeLists.txt
  example/65_gemm_multiply_multiply/moe_gemm1_xdl_fp8.cpp
  example/65_gemm_multiply_multiply/moe_gemm1_xdl_pk_i4.cpp
  example/65_gemm_multiply_multiply/moe_gemm2_xdl_fp8.cpp
  example/65_gemm_multiply_multiply/moe_gemm2_xdl_pk_i4.cpp
  include/ck/tensor_operation/gpu/block/blockwise_gemm_pipeline_xdlops_b_preshuffle_gufusion_dequant_v1.hpp
  include/ck/tensor_operation/gpu/block/blockwise_gemm_pipeline_xdlops_b_preshuffle_gufusion_v1.hpp
  include/ck/tensor_operation/gpu/block/blockwise_gemm_pipeline_xdlops_b_preshuffle_selector.hpp
  include/ck/tensor_operation/gpu/block/blockwise_gemm_pipeline_xdlops_base.hpp
  include/ck/tensor_operation/gpu/block/thread_group_tensor_slice_transfer_v4r1_gather.hpp
  include/ck/tensor_operation/gpu/block/thread_group_tensor_slice_transfer_v7r3_scatter.hpp
  include/ck/tensor_operation/gpu/device/impl/device_moe_gemm.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_moe_gemm.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v3r1_gather.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v7r3_scatter.hpp
  include/ck/utility/dynamic_buffer.hpp
  include/ck/utility/tuple_helper.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_moe_gemm.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_moe_gemm2.hpp
Labels: CI - Pass

#2115 Setup Doxygen API reference for Docs
  docs/conf.py
  docs/doxygen/Doxyfile
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation, ci:docs-only

#2134 [Tile Engine] Improved README.md
  tile_engine/ops/gemm/README.md
  tile_engine/ops/gemm/configs/instance_combination.json
Labels: documentation

#2147 updated Doxyfile and added the class list
  docs/doxygen/Doxyfile
  docs/index.rst
  docs/reference/Composable-Kernel-API-reference.rst
  docs/sphinx/_toc.yml.in
Labels: documentation, ci:docs-only

#2078 Add documentation for ck_tile::array<T,N>
  include/ck_tile/core/container/array.hpp
Labels: documentation
