Repository ROCm/composable_kernel, pull requests merged in 2025-06, with the labels that each got.

#2284 Code Refactor for check_err.hpp
  include/ck_tile/host/check_err.hpp
Labels: documentation

#2305 [CK_TILE] MUST USE INLINE FOR ANY NON TEMPLATE FUNCTION IN HEADER
  include/ck_tile/host/check_err.hpp
Labels: CI - Testing

#2243 [CK_TILE] fix build error in tile_add_rmsnorm2d_rdquant_fwd
  example/ck_tile/11_add_rmsnorm2d_rdquant/add_rmsnorm2d_rdquant_fwd.hpp
  example/ck_tile/11_add_rmsnorm2d_rdquant/example_add_rmsnorm2d_rdquant_fwd.cpp
Labels: bug, quality
