Repository ROCm/composable_kernel, pull requests merged in 2025-08, with the labels that each got.

#2647 trying a new set of conf files
  docs/Contributors_Guide.rst
  docs/conf.py
  docs/doxygen/Doxyfile
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation, ci:docs-only

#2656 Fixes to "General 2D Reduction Kernel" (#2535)
  include/ck_tile/core/utility/reduce_operator.hpp
  include/ck_tile/ops/reduce/block/block_reduce2d.hpp
  include/ck_tile/ops/reduce/kernel/reduce2d_kernel.hpp
  test/ck_tile/reduce/test_reduce2d.cpp
Labels: CI - Testing, urgency_high

#2658 Updates to create api ref
  docs/Contributors_Guide.rst
  docs/conf.py
  docs/doxygen/Doxyfile
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation, ci:docs-only

#2671 Re-enable optimization for gfx950 fmha fwd
  example/ck_tile/01_fmha/codegen/cpp_symbol_map.py
  example/ck_tile/01_fmha/codegen/ops/fmha_fwd.py
  example/ck_tile/01_fmha/fmha_fwd.cpp
  example/ck_tile/01_fmha/fmha_fwd.hpp
  example/ck_tile/01_fmha/script/benchmark_fwd.sh
  example/ck_tile/01_fmha/script/smoke_test_fwd.sh
  include/ck_tile/core/arch/amd_buffer_addressing.hpp
  include/ck_tile/core/arch/amd_buffer_addressing_builtins.hpp
  include/ck_tile/core/arch/arch.hpp
  include/ck_tile/core/arch/utility.hpp
  include/ck_tile/core/config.hpp
  include/ck_tile/core/numeric/bfloat16.hpp
  include/ck_tile/core/numeric/pk_fp4.hpp
  include/ck_tile/core/numeric/pk_int4.hpp
  include/ck_tile/core/numeric/vector_type.hpp
  include/ck_tile/ops/fmha.hpp
  include/ck_tile/ops/fmha/kernel/fmha_fwd_kernel.hpp
  include/ck_tile/ops/fmha/pipeline/block_fmha_pipeline_enum.hpp
  include/ck_tile/ops/fmha/pipeline/block_fmha_pipeline_problem.hpp
  include/ck_tile/ops/fmha/pipeline/block_fmha_pipeline_qr_ks_vs_async_trload.hpp
  include/ck_tile/ops/fmha/pipeline/block_fmha_pipeline_qr_ks_vs_async_trload_policy.hpp
  include/ck_tile/ops/fmha/pipeline/block_fmha_pipeline_qx_ks_vs_custom_policy.hpp
  include/ck_tile/ops/gemm/block/block_gemm_areg_breg_creg_v2.hpp
  include/ck_tile/ops/gemm/block/block_gemm_areg_breg_creg_v2_custom_policy.hpp
  include/ck_tile/ops/gemm/warp/warp_gemm.hpp
  include/ck_tile/ops/gemm/warp/warp_gemm_dispatcher.hpp
  include/ck_tile/ops/reduce/block/block_reduce.hpp
Labels: CI - Pass

#2675 Add padding to 1x1Stride1Pad0 conv specialization (bwd weight)
  include/ck/ck.hpp
  include/ck/tensor_operation/gpu/device/impl/device_grouped_conv_bwd_weight_xdl_cshuffle_v3.hpp
  include/ck/tensor_operation/operator_transform/transform_conv_bwd_weight_to_gemm.hpp
  include/ck/tensor_operation/operator_transform/transform_conv_bwd_weight_to_gemm_v2.hpp
Labels: on hold
