Repository ROCm/composable_kernel, pull requests merged in 2025-01, with the labels that each got.

#1786 Implement the fp16xint4 scale weight only kernel for Ali
  example/01_gemm/CMakeLists.txt
  example/01_gemm/gemm_xdl_fp16_pk_i4_v3_b_scale.cpp
  include/ck/tensor_operation/gpu/block/blockwise_gemm_pipeline_xdlops_b_scale_selector.hpp
  include/ck/tensor_operation/gpu/block/blockwise_gemm_pipeline_xdlops_v1_b_scale.hpp
  include/ck/tensor_operation/gpu/block/blockwise_gemm_pipeline_xdlops_v2_b_scale.hpp
  include/ck/tensor_operation/gpu/block/blockwise_gemm_pipeline_xdlops_v3_b_scale.hpp
  include/ck/tensor_operation/gpu/block/blockwise_gemm_pipeline_xdlops_v4_b_scale.hpp
  include/ck/tensor_operation/gpu/device/device_gemm_v2.hpp
  include/ck/tensor_operation/gpu/device/impl/device_gemm_xdl_cshuffle_v3_b_scale.hpp
  include/ck/tensor_operation/gpu/element/unary_element_wise_operation.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdl_cshuffle_v3_b_scale.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer.hpp
  include/ck/utility/amd_inline_asm.hpp
  include/ck/utility/data_type.hpp
  library/include/ck/library/tensor_operation_instance/gpu/gemm_b_scale.hpp
  library/src/tensor_operation_instance/gpu/gemm_b_scale/CMakeLists.txt
  library/src/tensor_operation_instance/gpu/gemm_b_scale/device_gemm_b_scale_xdl_f16_i4_f16/device_gemm_b_scale_xdl_f16_i4_f16_mk_nk_mn.hpp
  library/src/tensor_operation_instance/gpu/gemm_b_scale/device_gemm_b_scale_xdl_f16_i4_f16/device_gemm_b_scale_xdl_f16_i4_f16_mk_nk_mn_mem_v2_default_instance.cpp
  profiler/include/profiler/profile_gemm_b_scale_impl.hpp
  profiler/src/CMakeLists.txt
  profiler/src/profile_gemm_b_scale.cpp
Labels: enhancement, CI - Testing, priority

#1819 Implementing Test Filters for Smoke and Regression Tests
  .github/PULL_REQUEST_TEMPLATE.md
  CMakeLists.txt
  README.md
  example/CMakeLists.txt
  test/CMakeLists.txt
Labels: good first issue

#1820 fix a bug for int4 scale weight only kernel
  include/ck/utility/data_type.hpp
  include/ck/utility/dynamic_buffer.hpp
  profiler/include/profiler/profile_gemm_b_scale_impl.hpp
Labels: bug, CI - Testing
