Repository ROCm/composable_kernel, pull requests merged in 2025-03, with the labels that each got.

#1936 ck moe gemm implement
  example/65_gemm_multiply_multiply/CMakeLists.txt
  example/65_gemm_multiply_multiply/moe_gemm1_xdl_fp8.cpp
  example/65_gemm_multiply_multiply/moe_gemm2_xdl_fp8.cpp
  include/ck/library/utility/host_tensor.hpp
  include/ck/tensor_operation/gpu/block/blockwise_gemm_pipeline_xdlops_b_preshuffle_v1.hpp
  include/ck/tensor_operation/gpu/block/thread_group_tensor_slice_transfer_v4r1_gather.hpp
  include/ck/tensor_operation/gpu/block/thread_group_tensor_slice_transfer_v7r3_scatter.hpp
  include/ck/tensor_operation/gpu/device/impl/device_moe_gemm.hpp
  include/ck/tensor_operation/gpu/grid/gridwise_moe_gemm.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v3r1_gather.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v7r3_scatter.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_moe_gemm.hpp
  library/include/ck/library/reference_tensor_operation/cpu/reference_moe_gemm2.hpp
Labels: CI - Pass

#1972 ck_moe: fix useless code and remove usless oob
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v3r1_gather.hpp
  include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v7r3_scatter.hpp
Labels: enhancement

#1974 edit of the precision type content
  docs/index.rst
  docs/reference/Composable_Kernel_custom_types.rst
  docs/reference/Composable_Kernel_supported_scalar_types.rst
  docs/reference/Composable_Kernel_vector_utilities.rst
  docs/reference/precision_support.rst
  docs/sphinx/_toc.yml.in
Labels: documentation, ci:docs-only

#2007 Fix A/B lds transform
  include/ck_tile/ops/gemm/pipeline/gemm_universal_pipeline_ag_bg_cr_policy.hpp
Labels: enhancement

#1993 use fast path for sequence generation in old CK
  include/ck/utility/sequence.hpp
Labels: compilation time

#1908 creation of install doc and refactor of doc in general
  CONTRIBUTORS.md
  README.md
  docs/conceptual/Composable-Kernel-math.rst
  docs/conceptual/Composable-Kernel-structure.rst
  docs/conceptual/what-is-ck.rst
  docs/index.rst
  docs/install/Composable-Kernel-Docker.rst
  docs/install/Composable-Kernel-install.rst
  docs/install/Composable-Kernel-prerequisites.rst
  docs/install/dockerhub.rst
  docs/reference/Composable-Kernel-API-reference.rst
  docs/reference/Composable-Kernel-wrapper.rst
  docs/sphinx/_toc.yml.in
  docs/tutorial/Composable-Kernel-examples.rst
  docs/tutorial/tutorial_hello_world.rst
Labels: documentation, ci:docs-only
